---
buildDirectory: build
rethinkdbdash:
  password: ZworpWorpSchnodderaDorp
  servers:
  - host: localhost
    port: 28015
    db: alakrity_db
express: &EXP
  host: localhost
  protocol: https
  port: 3000
  api: /api/0/
auth:
  jwtExpiresIn: 2h
  jwtSecret: MuchSecretSuchWow
client: # The settings below are send to the client and are therefore not secure!
  api: *EXP # from the express settings.
