---
buildDirectory: build
rethinkdbdash:
  password: ZworpWorpSchnodderaDorp
  servers:
  - host: rethinkdb
    port: 28015
    db: alakrity_db
express:
  host: alakrity
  protocol: https
  port: 3000
  api: /api/0/
notifications:
  serverKey: AAAAOsSirME:APA91bE0UKJYxIONjTfTXWr4LlVt3eH-ZfM_bmERlUy47w_MB_IFt9wNHUiz5KbHwfO1dfpB7iy6qPSvmtX-1xqqQiBcUT-4MjQB8MjcAT19dmfc7qXHcBf9Lwe_ff9i2HUhOfC-l8cy
  senderID: 252407098561
#  webApiKey: AIzaSyBMuxYF20MiQu4HPY6N0m2ojQv032pzV_4
auth:
  jwtExpiresIn: 7d
  jwtSecret: b9GnojlIVvIpqSwGLqm$%t2wSIH8oQYm
client: # These Values are send to the client and are therefore not secure!
  apiUrl: https://alakrity.treehaus.space/api/0/
