---
buildDirectory: build
rethinkdbdash:
  password: <ProductionPassword>
  servers:
  - host: rethinkdb
    port: 28015
    db: alakrity_db
express:
  host: alakrity
  protocol: https
  port: 3000
  api: /api/0/
auth:
  jwtExpiresIn: 7d
  jwtSecret: <ComplicatedProductionSecret>
client: # These Values are send to the client and are therefore not secure!
  apiUrl: https://alakrity.treehaus.space/api/0/
