---
buildDirectory: build
rethinkdbdash:
  password: ZworpWorpSchnodderaDorp
  servers:
  - host: rethinkdb
    port: 28015
    db: alakrity_db
express:
  host: localhost
  port: 3000
  api: /api/0/
auth:
  jwtExpiresIn: 7d
  jwtSecret: b9GnojlIVvIpqSwGLqm$%t2wSIH8oQYm
client: # These Values are send to the client and are therefore not secure!
  apiUrl: https://alakrity.treehaus.space/api/0/
